# build the application
FROM microsoft/dotnet:sdk as build-env
ARG name
ARG BUILD_ENVIRONMENT=Debug

WORKDIR /app

COPY ./${name}/${name}.csproj ./${name}.csproj
RUN dotnet restore

COPY ./${name} .
RUN ls -l
RUN dotnet publish -c $BUILD_ENVIRONMENT -o out
RUN ls -l

# runtime container with built application
FROM microsoft/dotnet:aspnetcore-runtime
ARG name

WORKDIR /app

COPY --from=build-env /app/out ./

# can't use arg in ENTRYPOINT, so give a static name
RUN ln -s ./$name.dll entrypoint.dll
ENTRYPOINT ["dotnet", "entrypoint.dll"]
