# build the application
FROM microsoft/dotnet:sdk as build-env
ARG name
ARG BUILD_ENVIRONMENT=Debug

WORKDIR /app

COPY . ./
RUN cd "$name" && dotnet restore
RUN cd "$name" && dotnet publish -c $BUILD_ENVIRONMENT -o out

# runtime container with built application
FROM microsoft/dotnet:runtime
ARG name

WORKDIR /app

COPY --from=build-env /app/${name}/out .

# can't use arg in ENTRYPOINT, so give a static name
RUN ln -s ./$name.dll entrypoint.dll
ENTRYPOINT ["dotnet", "entrypoint.dll"]
